internet_bs_api:
  test_mode: true
  url_base: "https://api.internet.bs/"
  api_key: "replace_me"
  password: "replace_me"
  test_url_base: "https://testapi.internet.bs/"
  test_password: "testpass"
  test_api_key: "testapi"
